image: docker:19.03

services:
  - docker:19.03-dind

stages:
  - build
  - deploy

build-docker:
  only:
    - master
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  stage: build
  timeout: 10m
  script:
    - docker build --no-cache -t aiquanttech/aiquant:$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA -f Dockerfile .
    - export id=$(docker images aiquanttech/aiquant:$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA -q)
    - docker tag $id aiquanttech/aiquant:$CI_PROJECT_NAME-latest
    - docker push aiquanttech/aiquant:$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA
    - docker push aiquanttech/aiquant:$CI_PROJECT_NAME-latest;

deploy-staging:
  only:
    - master
  stage: deploy
  tags:
    - aiquant
    - deployment
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$TEMPORARY_RUNNER_SSH_PRIV" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $TEMPORARY_INTERNAL_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh runner-user@$TEMPORARY_INTERNAL_IP "/app/aiquant/$CI_PROJECT_NAME/run.sh"
